name: Fortipentest proxy server
on:
  push:
   branches: [ main ]
  pull_request:
   branches: [ main ]
jobs:
  build:
   runs-on: self-hosted
   steps:
   - uses: actions/checkout@v2
   - name: FPT_PROXY_SERVER
     run: |
        #env
        export FPTURL=https://sso.fortipentest.com EMAIL=kdeepak@fortinet.com ACCOUNTID=1422531 SCANURL=http://192.168.1.4:9503 SCANTYPE=0 FPTIP=10.36.234.13
        env | grep -E "FPTURL|EMAIL|ACCOUNTID|SCANURL|SCANTYPE|FPTIP" > /tmp/env
        #sudo docker pull registry.fortipentest.com/cicdfptproxyserver:latest
        sudo docker run --rm --env-file /tmp/env --network=host registry.fortipentest.com/cicdfptproxyserver:latest
        
