name: Fortipentest proxy server
on:
  push:
   branches: [ main ]
  pull_request:
   branches: [ main ]
jobs:
  build:
   runs-on: self-hosted
   steps:
   - uses: actions/checkout@v2
   - name: FPT_PROXY_SERVER
     run: |
        #env
        export EMAIL=kdeepak@fortinet.com FPTURL=https://sso.fortipentest.com LICENSE_SERIAL=FFPENT0000229751 APIKEY=ObZlPt77Stz+6LtrKcIOI1bSbCnf/9yeyCsBSk8KMlM= SCANURL=http://192.168.1.4:9600 SCANTYPE=0 UUID=69462f63-c3e7-49c5-9385-c846c63477f9
        env | grep -E "EMAIL|LICENSE_SERIAL|APIKEY|SCANURL|SCANTYPE|UUID|FPTURL" > /home/fortipentest/actions-runner/env
        sudo docker pull registry.fortipentest.com/cicdfptproxyserver:latest
        sudo docker run --rm --env-file /home/fortipentest/actions-runner/env --network=host --add-host sso.fortipentest.com:10.36.234.13 registry.fortipentest.com/cicdfptproxyserver:latest
        
